sudo: required

services:
  - docker

language: go

env:
  - TEST_SUITE=run-tests-local-process ARANGODB=arangodb:3.1 STARTER_MODES="single,cluster"
  - TEST_SUITE=run-tests-docker        ARANGODB=arangodb:3.1 STARTER_MODES="single,cluster"
  - TEST_SUITE=run-tests-local-process ARANGODB=arangodb/arangodb:latest STARTER_MODES="single,cluster"
  - TEST_SUITE=run-tests-docker        ARANGODB=arangodb/arangodb:latest STARTER_MODES="single,cluster"
  - TEST_SUITE=run-tests-local-process ARANGODB=arangodb/arangodb-preview:latest STARTER_MODES="single,cluster,resilientsingle"
  - TEST_SUITE=run-tests-docker        ARANGODB=arangodb/arangodb-preview:latest STARTER_MODES="single,cluster,resilientsingle"

script: make $TEST_SUITE

# 3.1 cluster startup is not always a success, causing lots of false positive.
matrix:
  allow_failures:
    - env: TEST_SUITE=run-tests-local-process ARANGODB=arangodb:3.1 STARTER_MODES="single,cluster"
    - env: TEST_SUITE=run-tests-docker        ARANGODB=arangodb:3.1 STARTER_MODES="single,cluster"

# Install Docker CE
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce